# Generated by Django 4.0.5 on 2022-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.CharField(max_length=40, unique=True, verbose_name='拼写')),
                ('pron', models.CharField(blank=True, max_length=40, null=True, verbose_name='音标')),
                ('zh', models.CharField(blank=True, max_length=40, null=True, verbose_name='汉译')),
                ('en', models.CharField(blank=True, max_length=40, null=True, verbose_name='英译')),
                ('remark', models.CharField(blank=True, max_length=400, null=True, verbose_name='备注')),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
            ],
        ),
    ]
