# Generated by Django 4.0.5 on 2022-06-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=400, null=True, verbose_name='句子')),
                ('translation', models.CharField(blank=True, max_length=400, null=True, verbose_name='译文')),
                ('remark', models.CharField(blank=True, max_length=400, null=True, verbose_name='备注')),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
    ]
