# Generated by Django 4.0.5 on 2022-06-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='prefix',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='前缀'),
        ),
        migrations.AddField(
            model_name='word',
            name='suffix',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='后缀'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='word',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='word',
            name='en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='英译'),
        ),
        migrations.AlterField(
            model_name='word',
            name='zh',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='汉译'),
        ),
    ]
